[workspace]
resolver = "2"
members = [
    "binding-cacher",
    "dao-cacher",
    "hypermap-cacher",
    "reset-cache",
    "set-nodes",
    "start-providing",
    "stop-providing"
]

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
