[dependencies]
anyhow = "1.0"
base64 = "0.21"
http = "1.0"
process_macros = "0.1"
rmp-serde = "1.1"
serde_json = "1.0"
sha2 = "0.10"
url = "2.5"
wit-bindgen = "0.42.1"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.hyperapp_macro]
git = "https://github.com/hyperware-ai/hyperapp-macro"
rev = "5c7cc7a"

[dependencies.hyperware-anthropic-sdk]
git = "https://github.com/hyperware-ai/hyperware-anthropic-sdk"
rev = "1fc7b0c"

[dependencies.hyperware-parse-wit]
path = "../crates/hyperware-parse-wit"

[dependencies.hyperware_process_lib]
features = ["hyperapp"]
git = "https://github.com/hyperware-ai/process_lib"
rev = "41f25ce"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.spider_caller_utils]
optional = true
path = "../target/spider-caller-utils"

[dependencies.uuid]
features = [
    "v4",
    "serde",
]
version = "1.4.1"

[dependencies.wit-parser]
features = ["serde"]
version = "0.220.0"

[features]
caller-utils = ["spider_caller_utils"]
public-mode = []
simulation-mode = []

[lib]
crate-type = ["cdylib"]

[package]
edition = "2021"
name = "spider"
version = "0.1.0"

[package.metadata.component]
package = "hyperware:process"
