[dependencies]
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.21"
hyperapp_macro = "0.1.1"
process_macros = "0.1"
serde_json = "1.0"
wit-bindgen = "0.42.1"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.hyperware-elevenlabs-tts]
git = "https://github.com/hyperware-ai/hyperware-elevenlabs-tts"
rev = "f9f49c5"

[dependencies.hyperware-openai-stt]
git = "https://github.com/hyperware-ai/hyperware-openai-ttstt"
rev = "fb6ea25"

[dependencies.hyperware-openai-tts]
git = "https://github.com/hyperware-ai/hyperware-openai-ttstt"
rev = "fb6ea25"

[dependencies.hyperware_process_lib]
features = ["hyperapp"]
git = "https://github.com/hyperware-ai/process_lib"
rev = "1a6ad9d"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.uuid]
features = [
    "v4",
    "serde",
]
version = "1.0"

[features]
simulation-mode = []

[lib]
crate-type = ["cdylib"]

[package]
edition = "2021"
name = "ttstt"
version = "0.1.0"

[package.metadata.component]
package = "hyperware:process"
